#'////////////////////////////////////////////////////////////////////////////
#' FILE: testthat.R
#' AUTHOR: David Ruvolo
#' CREATED: 2020-08-10
#' MODIFIED: 2020-08-10
#' PURPOSE: main testhat file
#' STATUS: working
#' PACKAGES: testthat; rheroicons
#' COMMENTS: this file was generated by `dev/dev.R`
#'////////////////////////////////////////////////////////////////////////////

# pkgs
library(testthat)
library(rheroicons)

# test
test_check("rheroicons")
